@startuml
package api {
    class Api {
        Service
        Request
        Response
        利用者のリクエストを牌に変換するくん
        invoke(List<牌>) : Response
    }
    class Response {
        response : Map<String,String>
        和了役をリストで返す : List<Map<String,String>>
    }
    Api .> Request
    Api .> Response

    class Request {
        1つ目 : String
        2つ目 : String
        3つ目 : String
        4つ目 : String
        5つ目 : String
        6つ目 : String
        7つ目 : String
        8つ目 : String
        9つ目 : String
        10つ目 : String
        11つ目 : String
        12つ目 : String
        13つ目 : String
        14つ目 : String
        リクエストを作成(List<String>) : List<String>
    }
}
package service{
    class Service{
        並べるくん
        役の判定くん
        + 和了点数を返す(List<牌>) : 和了内容
    }
}

Api ..> Service
package domain {
    package 和了点数 {
        class 和了点数計算くん{
            和了内容
            和了点数を計算(List<牌>) : 和了内容
        }
        enum 点数表{}
        class 和了点数 {
            和了点数 : int
        }
        class 和了内容{
            List<牌>
            List<和了役>
            合計符
            和了点数
            和了内容を生成() : 和了内容
        }
        和了点数計算くん ..> 点数表
        和了点数計算くん ..> 和了点数
        和了点数計算くん ..> 和了内容
    }

    package 符 {
        class 合計符計算くん{
            副底
            和了方
            面子
            省頭
            待の形の種類
            合計符計算(List<牌>) : 合計符
        }
        class 合計符 {
            合計符 : int
        }

        合計符計算くん .> 合計符
    }

    package 牌 {
        interface 牌
        class 並べるくん {
            並べたリスト : List<牌>
            牌の種類ごとに並べる(List<牌>) : List<牌>
        }
        class 利用者のリクエストを牌に変換するくん {
            リクエストコードのチェック(List<String>)) : boolean
            リクエストを牌に変換(List<Request>) : List<牌>
            牌に変換(String) : 牌
        }
        package 数牌 {

            enum 索子 {
                牌の種類() : String
                牌の名前() : String
                牌のリクエストコード() : String
                {static} + 索子か(String) : boolean
                {static} + 索子のうちどれか(String) : 索子
                {static} + 19字牌か(牌) : boolean
            }

            enum 萬子 {
                牌の種類() : String
                牌の名前() : String
                牌のリクエストコード() : String
                {static} + 萬子か(String) : boolean
                {static} + 萬子のうちどれか(String) : 萬子
                {static} + 19字牌か(牌) : boolean

            }

            enum 筒子 {
                牌の種類() : String
                牌の名前() : String
                牌のリクエストコード() : String
                {static} + 萬子か(String) : boolean
                {static} + 萬子のうちどれか(String) : 萬子
                {static} + 19字牌か(牌) : boolean

            }
        }

        package 字牌 {

            enum 三元牌 {
                白
                發
                中
                牌の種類() : String
                牌の名前() : String
                牌のリクエストコード() : String
                {static} + 三元牌か(String) : boolean
                {static} + 三元牌のうちどれか(String) : 三元牌
            }

            enum 風牌 {
                東
                南
                西
                北
                牌の種類() : String
                牌の名前() : String
                牌のリクエストコード() : String
                {static} + 風牌か(String) : boolean
                {static} + 風牌のうちどれか(String) : 風牌
            }
        }
        索子 --|> 牌
        萬子 --|> 牌
        筒子 --|> 牌
        三元牌 --|> 牌
        風牌 --|> 牌
        並べるくん ..> 索子
        並べるくん ..> 萬子
        並べるくん ..> 筒子
        並べるくん ..> 三元牌
        並べるくん ..> 風牌
        利用者のリクエストを牌に変換するくん ...> 索子
        利用者のリクエストを牌に変換するくん ...> 萬子
        利用者のリクエストを牌に変換するくん ...> 筒子
        利用者のリクエストを牌に変換するくん ...> 三元牌
        利用者のリクエストを牌に変換するくん ...> 風牌
    }

    package 役 {
        class 和了役 {
            役の名前 : String
            役の飜数 : String
        }
        class 和了役判定くん {
            順子
            刻子
            役満の判定
            1飜の判定
            2飜の判定
            3飜の判定
            5飜の判定
            6飜の判定
            和了役を返す(List<牌>) : List<和了役>
        }
        和了役判定くん .> 和了役
        和了役判定くん ..> 役の判定

        package 役の判定 {
            class 1飜の判定 {
            }
            class 2飜の判定{
            }
            class 3飜の判定{
            }
            class 5飜の判定{
            }
            class 6飜の判定{
            }
            class 役満の判定{
            }
        }
        package 役一覧{
            enum 1飜 {
                役名() : String
                飜数() : int
                飜数() : String
            }
            enum 2飜 {
                役名() : String
                飜数() : int
                飜数() : String
            }
            enum 3飜 {
                役名() : String
                飜数() : int
                飜数() : String
            }
            enum 5飜 {
                役名() : String
                飜数() : int
                飜数() : String
            }
            enum 6飜 {
                役名() : String
                飜数() : int
                飜数() : String
            }
            enum 役満 {
                役名() : String
                飜数() : int
                飜数() : String
            }
        }
        和了役判定くん ..> 役一覧
    }

    package 面子 {
        class 面子判定くん{
            is33332(List<牌>):boolean
        }
        enum 順子{
            {static} どの順子が含まれているか(List<牌>):List<順子>
        }
        enum 刻子{
            {static} どの刻子が含まれているか(List<牌>):List<刻子>
        }
        enum 対子{
            {static} どの対子が含まれているか(List<牌>):List<対子>
        }

        面子判定くん..>順子
        面子判定くん..>刻子
        面子判定くん..>対子
    }
    和了点数 .>符
    和了点数 .> 役
    和了点数 .> 牌
    面子 ..> 牌
    符 ...> 面子
    符 ...> 牌
    役 ..> 牌
    役 ..> 面子
}
Service ..> 和了点数計算くん

@enduml
